In [24]:
import pandas as pd
import numpy as np

In [15]:
df = pd.read_csv('pesquisa_satisfacao.csv', sep=';')
df

         Cliente Satisfação  Tempo de Espera (min)
0         Naruto       Alta                      8
1           Goku       Alta                     10
2         Vegeta      Média                     17
3         Sasuke       Alta                      8
4         Madara      Média                     15
5          Luffy      Baixa                      5
6           Zoro       Alta                     22
7          Sanji      Baixa                     26
8         Yusuke      Baixa                     14
9         Kurama      Média                      8
10           Gon      Média                     12
11          Eren      Média                     28
12        Mikasa       Alta                      6
13         Light       Alta                     10
14             L       Alta                     19
15  Peter Parker      Baixa                     21
16   Bruce Wayne       Alta                     18
17        Thanos      Média                     19
18       Edmundo      Baixa                     13
19       Vegetti      Média                     19

In [16]:
media_satisfacao = df.groupby('Satisfação')['Tempo de Espera (min)'].mean().reset_index()
media_satisfacao['Tempo de Espera (min)'] = media_satisfacao['Tempo de Espera (min)'].round(2)
media_satisfacao

  Satisfação  Tempo de Espera (min)
0       Alta                  12.62
1      Baixa                  15.80
2      Média                  16.86

In [17]:
df_anp = pd.read_csv('ANP2025.csv', sep=';')
df_anp

C:\Users\luis.falcao\AppData\Local\Temp\ipykernel_6096\3435742200.py:1: DtypeWarning: Columns (0,1,2,3,4,5,6,7,8,9,10,11,12,14,15) have mixed types. Specify dtype option on import or set low_memory=False.
  df_anp = pd.read_csv('ANP2025.csv', sep=';')

,Regiao - Sigla,Estado - Sigla,Municipio,Revenda,CNPJ da Revenda,Nome da Rua,Numero Rua,Complemento,Bairro,Cep,Produto,Data da Coleta,Valor de Venda,Valor de Compra,Unidade de Medida,Bandeira
0,NE,CE,SOBRAL,ECONOGÁS DO BRASIL DIST. DERIV. DE PET. BIOC. ...,08.775.979/0002-62,RUA TABELIÃO IDELFONSO CAVALCANTI,455,NaN,CENTRO,62010-000,GASOLINA,01/01/2025,"6,29",NaN,R$ / litro,RAIZEN
1,NE,CE,SOBRAL,ECONOGÁS DO BRASIL DIST. DERIV. DE PET. BIOC. ...,08.775.979/0002-62,RUA TABELIÃO IDELFONSO CAVALCANTI,455,NaN,CENTRO,62010-000,GASOLINA ADITIVADA,01/01/2025,"6,49",NaN,R$ / litro,RAIZEN
2,NE,CE,SOBRAL,ECONOGÁS DO BRASIL DIST. DERIV. DE PET. BIOC. ...,08.775.979/0002-62,RUA TABELIÃO IDELFONSO CAVALCANTI,455,NaN,CENTRO,62010-000,DIESEL S10,01/01/2025,"6,19",NaN,R$ / litro,RAIZEN
3,NE,CE,SOBRAL,ECONOGÁS DO BRASIL DIST. DERIV. DE PET. BIOC. ...,08.775.979/0002-62,RUA TABELIÃO IDELFONSO CAVALCANTI,455,NaN,CENTRO,62010-000,ETANOL,01/01/2025,"5,19",NaN,R$ / litro,RAIZEN
4,NE,CE,SOBRAL,V.C.EMPREENDIMENTOS LTDA,03.551.935/0002-35,AVENIDA JOSE EUCLIDES FERREIRA GOMES,30,POSTO FLASH,CORACAO DE JESUS,62043-070,GASOLINA,01/01/2025,"6,53",NaN,R$ / litro,RAIZEN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
429518,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
429519,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
429520,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
429521,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
429522,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [18]:
df_anp_rj = df_anp.loc[df_anp['Estado - Sigla'] == 'RJ']
df_anp_rj.head(5)

,Regiao - Sigla,Estado - Sigla,Municipio,Revenda,CNPJ da Revenda,Nome da Rua,Numero Rua,Complemento,Bairro,Cep,Produto,Data da Coleta,Valor de Venda,Valor de Compra,Unidade de Medida,Bandeira
54,SE,RJ,CAMPOS DOS GOYTACAZES,POSTO DE COMBUSTIVEIS CONTORNO DE CAMPOS LTDA,31.212.889/0002-85,AVENIDA NILO PECANHA,614,/822 PATIO,PQ SANTO AMARO,28030-035,GNV,01/01/2025,"5,39",NaN,R$ / m³,VIBRA
55,SE,RJ,CAMPOS DOS GOYTACAZES,POSTO DE COMBUSTIVEIS CONTORNO DE CAMPOS LTDA,31.212.889/0002-85,AVENIDA NILO PECANHA,614,/822 PATIO,PQ SANTO AMARO,28030-035,GASOLINA,01/01/2025,"6,49",NaN,R$ / litro,VIBRA
56,SE,RJ,CAMPOS DOS GOYTACAZES,POSTO DE COMBUSTIVEIS CONTORNO DE CAMPOS LTDA,31.212.889/0002-85,AVENIDA NILO PECANHA,614,/822 PATIO,PQ SANTO AMARO,28030-035,GASOLINA ADITIVADA,01/01/2025,"6,69",NaN,R$ / litro,VIBRA
57,SE,RJ,CAMPOS DOS GOYTACAZES,POSTO DE COMBUSTIVEIS CONTORNO DE CAMPOS LTDA,31.212.889/0002-85,AVENIDA NILO PECANHA,614,/822 PATIO,PQ SANTO AMARO,28030-035,ETANOL,01/01/2025,"4,79",NaN,R$ / litro,VIBRA
58,SE,RJ,CAMPOS DOS GOYTACAZES,POSTO DE COMBUSTIVEIS B J LTDA,06.211.735/0001-40,RUA BENEDITO QUEIROZ,1,NaN,TURF CLUB,28024-040,GASOLINA,01/01/2025,"6,42",NaN,R$ / litro,BRANCA

In [19]:
df_anp_rj['Valor de Venda'] = df_anp_rj['Valor de Venda'].str.replace(',','.').astype(float)

C:\Users\luis.falcao\AppData\Local\Temp\ipykernel_6096\3965459454.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_anp_rj['Valor de Venda'] = df_anp_rj['Valor de Venda'].str.replace(',','.').astype(float)

In [23]:
media_munic_rj = df_anp_rj.groupby('Municipio')['Valor de Venda'].mean().reset_index()
media_munic_rj = media_munic_rj.sort_values(by='Valor de Venda', ascending=False)
media_munic_rj

                 Municipio  Valor de Venda
0           ANGRA DOS REIS        6.470086
10                   MACAE        6.224548
24               TRES RIOS        6.206138
2           BARRA DO PIRAI        6.168793
23               SAQUAREMA        6.070452
9                ITAPERUNA        6.069675
16              PETROPOLIS        6.064262
1                 ARARUAMA        6.030011
5                CABO FRIO        6.029144
6    CAMPOS DOS GOYTACAZES        6.020561
14           NOVA FRIBURGO        6.010355
26           VOLTA REDONDA        5.990214
25                 VALENCA        5.945307
3              BARRA MANSA        5.891807
20  SANTO ANTONIO DE PADUA        5.864975
11                  MARICA        5.750767
18              RIO BONITO        5.743828
17                 RESENDE        5.648785
19          RIO DE JANEIRO        5.639952
15             NOVA IGUACU        5.617374
8                 ITABORAI        5.559130
4             BELFORD ROXO        5.554597
21             SAO GONCALO        5.543540
7          DUQUE DE CAXIAS        5.522046
22      SAO JOAO DE MERITI        5.515125
12               NILOPOLIS        5.490146
13                 NITEROI        5.488851

In [25]:

array_valor_venda = np.array(media_munic_rj['Valor de Venda'])

In [26]:
media = np.mean(array_valor_venda)
mediana = np.median(array_valor_venda)
q1 = np.quantile(array_valor_venda, 0.25)
q2 = np.quantile(array_valor_venda, 0.50)
q3 = np.quantile(array_valor_venda, 0.75)

print(f'A média é {media}')
print(f'A mediana é {mediana}')
print(f'Primeiro quartil (Q1): {q1}')
print(f'Segundo quartil (Q2, Mediana): {q2}')
print(f'Terceiro quartil (Q3): {q3}')

A média é 5.856684177816972
A mediana é 5.891806930693069
Primeiro quartil (Q1): 5.588252288329519
Segundo quartil (Q2, Mediana): 5.891806930693069
Terceiro quartil (Q3): 6.047136868364782

In [27]:
munic_acima_q3 = media_munic_rj.loc[media_munic_rj['Valor de Venda'] > q3]
munic_acima_q3

         Municipio  Valor de Venda
0   ANGRA DOS REIS        6.470086
10           MACAE        6.224548
24       TRES RIOS        6.206138
2   BARRA DO PIRAI        6.168793
23       SAQUAREMA        6.070452
9        ITAPERUNA        6.069675
16      PETROPOLIS        6.064262